version: 2.1
orbs:
  node: circleci/node@3.0.1
jobs:
  build-and-test:
    environment:
      GATSBY_WP_URL: admin.cascading-news.com
      GATSBY_WP_PROTOCOL: https
      GATSBY_REPLACEMENT_URL: http://localhost:8000
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn eslint
            - run: yarn type-check
            - run: yarn test
            - run: yarn build
workflows:
  build-and-test:
    jobs:
      - build-and-test
