name: Trigger Netlify Build
on:
  schedule:
    # At minute 0 past every 12th hour. https://crontab.guru/every-12-hours
    - cron: '0 */12 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5e8b2ff63489e4823369227d
